apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream-mithun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upstream-mithun
  template:
    metadata:
      labels:
        app: upstream-mithun
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"   
    spec:
      containers:
        - name: upstream-mithun
          image: mithun100/nodejs-upstream:latest
          ports:
            - containerPort: 4444
          env:
          - name: DOWNSTREAM_URL
            value: "http://downstream-mithun.default.svc.cluster.local:80"
